// Fix: Import RosterEntry to resolve type error.
import { ShiftType, ShiftColorSettings, RosterEntry } from './types';

export const SHIFT_TYPES: ShiftType[] = Object.values(ShiftType);

export const NIGHT_SHIFTS: ShiftType[] = [ShiftType.T2GN, ShiftType.PM17, ShiftType.CRON];
export const DAY_SHIFTS: ShiftType[] = [ShiftType.T2GD, ShiftType.AM18, ShiftType.CROD];

export const DEFAULT_SHIFT_COLORS: ShiftColorSettings = {
  [ShiftType.OFF]: { background: '#E5E7EB', text: '#374151' },
  [ShiftType.AM18]: { background: '#FED7AA', text: '#9A3412' },
  [ShiftType.PM17]: { background: '#FDE68A', text: '#92400E' },
  [ShiftType.T2GD]: { background: '#86EFAC', text: '#14532D' },
  [ShiftType.T2GN]: { background: '#BEF264', text: '#365314' },
  [ShiftType.CROD]: { background: '#A5F3FC', text: '#155E75' },
  [ShiftType.CRON]: { background: '#7DD3FC', text: '#0C4A6E' },
  [ShiftType.AL]: { background: '#93C5FD', text: '#1E3A8A' },
};

export const INITIAL_ROSTER_DATA: RosterEntry[] = [
  { id: 1, empNo: '405745', fusionId: '4831', name: 'SHAFI ALI CHOUGLE', terminalId: 'T1', role: 'GAS-Clerk', schedule: [ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF] },
  { id: 2, empNo: '423012', fusionId: '12680', name: 'ZUBAIR. BALOCH', terminalId: 'T1', role: 'GAS-Clerk', schedule: [ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.CROD, ShiftType.CRON, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18] },
  { id: 3, empNo: '418212', fusionId: '5397', name: 'MATEE MASOOD', terminalId: 'T1', role: 'GAS-Clerk', schedule: [ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.CRON, ShiftType.CRON, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17] },
  { id: 4, empNo: '416013', fusionId: '12583', name: 'TITO CERRADO', terminalId: 'T1', role: 'GAS-Clerk', schedule: [ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18] },
  { id: 5, empNo: '420917', fusionId: '5982', name: 'DILSHAD RASHEED', terminalId: 'T2', role: 'GAS-Clerk', schedule: [ShiftType.PM17, ShiftType.OFF, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF] },
  { id: 6, empNo: '420897', fusionId: '5978', name: 'MOHAMMED ISMAIL', terminalId: 'T2', role: 'GAS-Clerk', schedule: [ShiftType.T2GD, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.CROD, ShiftType.CROD, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF] },
  { id: 7, empNo: '136599', fusionId: '136599', name: 'MAZAR PARKAR', terminalId: 'T2', role: 'GAS-Clerk', schedule: [ShiftType.PM17, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF] },
  { id: 8, empNo: '217468', fusionId: '217468', name: 'MARIA', terminalId: 'T2', role: 'GAS-Clerk', schedule: [ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.CROD, ShiftType.CROD, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.CROD, ShiftType.CROD, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18] },
  { id: 9, empNo: '424472', fusionId: '12835', name: 'MOHAMED MBARAK', terminalId: 'T3', role: 'GAS-Clerk', schedule: [ShiftType.AM18, ShiftType.PM17, ShiftType.CRON, ShiftType.CRON, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.CRON, ShiftType.CRON, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17] },
  { id: 10, empNo: '184901', fusionId: '184901', name: 'MOHAMMED IRFAN', terminalId: 'T3', role: 'GAS-Clerk', schedule: [ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.T2GN, ShiftType.T2GN, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF] },
  { id: 11, empNo: '423036', fusionId: '12687', name: 'MOHAMMED OSMAN', terminalId: 'T3', role: 'GAS-Clerk', schedule: [ShiftType.CRON, ShiftType.CRON, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.CROD, ShiftType.CRON, ShiftType.CRON, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AL, ShiftType.AL, ShiftType.OFF, ShiftType.OFF, ShiftType.OFF, ShiftType.OFF] },
  { id: 12, empNo: '423703', fusionId: '12758', name: 'SYDAIN ALI', terminalId: 'T3', role: 'GAS-Clerk', schedule: [ShiftType.OFF, ShiftType.AM18, ShiftType.CROD, ShiftType.CROD, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF] },
  { id: 13, empNo: '424757', fusionId: '12867', name: 'AMAD HUSSAIN', terminalId: 'T3', role: 'GAS-Clerk', schedule: [ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF] },
  { id: 14, empNo: '184806', fusionId: '184806', name: 'MOHAMMED ASHIF', terminalId: 'T4', role: 'GAS-Clerk', schedule: [ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18] },
  { id: 15, empNo: '418053', fusionId: '12597', name: 'ABDUL SHAKOOR', terminalId: 'T4', role: 'GAS-Clerk', schedule: [ShiftType.CROD, ShiftType.CROD, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.CROD, ShiftType.CROD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17] },
  { id: 16, empNo: '184336', fusionId: '184336', name: 'MOHAMMED RAAJID', terminalId: 'T4', role: 'GAS-Clerk', schedule: [ShiftType.AL, ShiftType.AL, ShiftType.AL, ShiftType.AL, ShiftType.AL, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.CRON, ShiftType.CRON, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.CRON] },
  { id: 17, empNo: '422922', fusionId: '12671', name: 'MOHAMED HAJA SAYED', terminalId: 'T4', role: 'GAS-Clerk', schedule: [ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.CRON, ShiftType.T2GN, ShiftType.T2GN, ShiftType.OFF, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.AM18] },
  { id: 18, empNo: '184342', fusionId: '184342', name: 'MIDHUN JAMES', terminalId: 'T4', role: 'GAS-Clerk', schedule: [ShiftType.AL, ShiftType.OFF, ShiftType.PM17, ShiftType.PM17, ShiftType.T2GN, ShiftType.T2GN, ShiftType.PM17, ShiftType.PM17, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.AM18, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.T2GD, ShiftType.T2GD, ShiftType.PM17, ShiftType.PM17, ShiftType.CRON, ShiftType.OFF, ShiftType.OFF, ShiftType.AM18, ShiftType.T2GD, ShiftType.AM18, ShiftType.AM18, ShiftType.CROD] },
];